table dim_station
	lineageTag: a9ba5075-928e-512f-9a53-609e4c9032a7

	column station_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1ff443bc-9222-5cb4-8d44-38f989b34c47
		summarizeBy: none
		sourceColumn: station_key

		annotation SummarizationSetBy = User

	column station_code
		dataType: string
		lineageTag: 6fdb9bb5-5fde-5cd9-8ab3-30e7f1b7043a
		summarizeBy: none
		sourceColumn: station_code

		annotation SummarizationSetBy = User

	column station_name
		dataType: string
		lineageTag: c043f623-ee9d-5429-bf9a-3a9ed8b7b8a0
		summarizeBy: none
		sourceColumn: station_name

		annotation SummarizationSetBy = User

	column station_label
		dataType: string
		lineageTag: a98a0207-29e1-5ea6-8088-2062c3854e7b
		summarizeBy: none
		sourceColumn: station_label

		annotation SummarizationSetBy = User

	column line_code
		dataType: string
		lineageTag: c88a06ec-218e-542a-873e-be128100bb97
		summarizeBy: none
		sourceColumn: line_code

		annotation SummarizationSetBy = User

	column location_type
		dataType: string
		lineageTag: 45c90a4c-a2f4-5bf4-b906-63fbe7a90a54
		summarizeBy: none
		sourceColumn: location_type

		annotation SummarizationSetBy = User

	column is_station
		dataType: boolean
		lineageTag: 5cdb20a9-d817-5320-b455-457c22e8ad86
		summarizeBy: none
		sourceColumn: is_station

		annotation SummarizationSetBy = User

	column opened
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e8e8c5ab-727d-5fb1-b995-ba347b07ccb9
		summarizeBy: none
		sourceColumn: opened

		annotation SummarizationSetBy = User

	column closed
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a9292e03-9752-5c22-8db9-5a3ce4d6499e
		summarizeBy: none
		sourceColumn: closed

		annotation SummarizationSetBy = User

	partition dim_station = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_station.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.TransformColumns(Promoted, {}, each if _ = "" then null else _),
				    Typed = Table.TransformColumnTypes(Blanks, {{"station_key", Int64.Type}, {"station_code", type text}, {"station_name", type text}, {"station_label", type text}, {"line_code", type text}, {"location_type", type text}, {"is_station", type logical}, {"opened", type date}, {"closed", type date}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
