table dim_date
	lineageTag: c1c122e3-6b3b-521c-aa8d-ee55f9433d78
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 64905b3f-3e11-5863-8139-5c202a9f1569
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = User

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 835b48f2-aa9d-5689-bc65-fa9a8fd9c8e5
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = User

	column year
		dataType: int64
		formatString: 0
		lineageTag: cd73d671-41f4-5666-b192-bf834ad14398
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 695f886e-cb57-5479-8f54-be320f7aa5cf
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = User

	column month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f319046b-2fa6-5d7c-a458-b82503837278
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column month_name
		dataType: string
		lineageTag: 4c08dc3f-cebd-54f9-bc9e-6e537ad4de40
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		annotation SummarizationSetBy = User

	column month_start
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: 88c42238-b71f-5a56-a52a-20f07baba7f1
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = User

	column year_month
		dataType: string
		lineageTag: 8be68913-4eb2-51de-a05d-e03e0f1c7aaf
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = User

	column day_of_week
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1d658791-e450-5977-864b-07533084d349
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = User

	column day_name
		dataType: string
		lineageTag: d270ede3-bda6-5ae9-a4c0-d8a13e1d02ba
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		annotation SummarizationSetBy = User

	column is_weekend
		dataType: boolean
		lineageTag: c80f635e-a00b-56ed-97da-74c1813dd9ce
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = User

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.TransformColumns(Promoted, {}, each if _ = "" then null else _),
				    Typed = Table.TransformColumnTypes(Blanks, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"month_start", type date}, {"year_month", type text}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
