table station_ranking
	lineageTag: 6202a891-cebc-542d-911f-016ba33c58c3

	/// Incidents at the station in the selected ranking period.
	measure 'Station Incidents' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( SUM ( station_ranking[incidents] ), station_ranking[period] = p )
		formatString: #,0
		displayFolder: Ranking
		lineageTag: e8150efb-526b-532b-b885-e598964db11e

		annotation SqlTwin = station_ranking_all.incidents

	/// The station's own minutes per incident.
	measure 'Naive Minutes per Incident' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( AVERAGE ( station_ranking[naive_minutes_per_incident] ), station_ranking[period] = p )
		formatString: 0.00
		displayFolder: Ranking
		lineageTag: 739330e0-b7f1-55fa-9b33-397cb3a4bdb4

		annotation SqlTwin = station_ranking_all.naive_minutes_per_incident

	/// Minutes per incident across the station's line.
	measure 'Line Minutes per Incident' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( AVERAGE ( station_ranking[line_minutes_per_incident] ), station_ranking[period] = p )
		formatString: 0.00
		displayFolder: Ranking
		lineageTag: a94ba12f-5ff8-55e8-b21b-425ebace0f8b

		annotation SqlTwin = station_ranking_all.line_minutes_per_incident

	/// How far the estimate moved toward the line rate (0% = not at all).
	measure 'Shrinkage Weight' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( AVERAGE ( station_ranking[shrinkage_weight] ), station_ranking[period] = p )
		formatString: 0%
		displayFolder: Ranking
		lineageTag: ed869fb1-8607-58f5-bb21-1dcb0e21169f

		annotation SqlTwin = station_ranking_all.shrinkage_weight

	/// Empirical-Bayes estimate of minutes per incident.
	measure 'Shrunk Minutes per Incident' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( AVERAGE ( station_ranking[shrunk_minutes_per_incident] ), station_ranking[period] = p )
		formatString: 0.00
		displayFolder: Ranking
		lineageTag: e6a03d26-2572-5e29-b63e-36f13f15413e

		annotation SqlTwin = station_ranking_all.shrunk_minutes_per_incident

	/// Rank by the station's own rate (1 = most minutes per incident).
	measure 'Naive Rank' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( MIN ( station_ranking[naive_rank] ), station_ranking[period] = p )
		formatString: 0
		displayFolder: Ranking
		lineageTag: 8aab0d8c-7550-5741-b7e7-75d7c7cd3c12

		annotation SqlTwin = station_ranking_all.naive_rank

	/// Rank by the shrunk rate (1 = least reliable).
	measure 'Shrunk Rank' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( MIN ( station_ranking[shrunk_rank] ), station_ranking[period] = p )
		formatString: 0
		displayFolder: Ranking
		lineageTag: b4c120ab-d029-5126-bd3e-a5953be3c089

		annotation SqlTwin = station_ranking_all.shrunk_rank

	/// Naive rank minus shrunk rank (positive = looks worse after shrinkage).
	measure 'Rank Change' =
			VAR p =
			    IF ( HASONEVALUE ( station_ranking[period] ), VALUES ( station_ranking[period] ), "All years" )
			RETURN
			    CALCULATE ( SUM ( station_ranking[rank_change] ), station_ranking[period] = p )
		formatString: +0;-0;0
		displayFolder: Ranking
		lineageTag: c7f05c2d-dfb9-512b-9e03-b3b90cfefeed

		annotation SqlTwin = station_ranking_all.rank_change

	column period
		dataType: string
		lineageTag: ea226a57-4a2f-5748-8770-1d540dd76bc9
		summarizeBy: none
		sourceColumn: period
		sortByColumn: period_sort

		annotation SummarizationSetBy = User

	column period_sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1707f576-782d-53ed-8dee-9b1dd65720f4
		summarizeBy: none
		sourceColumn: period_sort

		annotation SummarizationSetBy = User

	column period_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bf327649-3324-55e0-a738-6537a9210750
		summarizeBy: none
		sourceColumn: period_start

		annotation SummarizationSetBy = User

	column period_end
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a146b606-894f-5479-80a7-5f9d9f482bc2
		summarizeBy: none
		sourceColumn: period_end

		annotation SummarizationSetBy = User

	column station_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee38491b-ac7c-5294-9620-87820e3d0caa
		summarizeBy: none
		sourceColumn: station_key

		annotation SummarizationSetBy = User

	column station_label
		dataType: string
		lineageTag: d257395b-5b89-580e-8522-3057cb12ffe1
		summarizeBy: none
		sourceColumn: station_label

		annotation SummarizationSetBy = User

	column line_code
		dataType: string
		lineageTag: 4666a048-2834-5cc9-a6dd-705c57a2dd26
		summarizeBy: none
		sourceColumn: line_code

		annotation SummarizationSetBy = User

	column incidents
		dataType: int64
		formatString: #,0
		lineageTag: 16051875-512b-54a2-b695-7cff07c24382
		summarizeBy: sum
		sourceColumn: incidents

		annotation SummarizationSetBy = User

	column delay_minutes
		dataType: double
		formatString: #,0
		lineageTag: b52712d3-8c89-5d3a-a63a-d39badc62708
		summarizeBy: sum
		sourceColumn: delay_minutes

		annotation SummarizationSetBy = User

	column naive_minutes_per_incident
		dataType: double
		formatString: 0.00
		lineageTag: 9caac408-5653-5a79-bafc-2d75e1187274
		summarizeBy: none
		sourceColumn: naive_minutes_per_incident

		annotation SummarizationSetBy = User

	column line_minutes_per_incident
		dataType: double
		formatString: 0.00
		lineageTag: 54cfb6a1-e9d1-5fa0-8408-700589e63075
		summarizeBy: none
		sourceColumn: line_minutes_per_incident

		annotation SummarizationSetBy = User

	column within_variance
		dataType: double
		formatString: 0.00
		lineageTag: 61e1232b-ba1f-5c93-b18f-371f96d66071
		summarizeBy: none
		sourceColumn: within_variance

		annotation SummarizationSetBy = User

	column line_within_variance
		dataType: double
		formatString: 0.00
		lineageTag: 9490d4de-c744-5b45-8e06-816f50bc4c5b
		summarizeBy: none
		sourceColumn: line_within_variance

		annotation SummarizationSetBy = User

	column between_variance
		dataType: double
		formatString: 0.000
		lineageTag: 2a4d1af2-5ddc-576d-b6c9-ae3b71d22e33
		summarizeBy: none
		sourceColumn: between_variance

		annotation SummarizationSetBy = User

	column shrinkage_weight
		dataType: double
		formatString: 0%
		lineageTag: 11b12f4d-c6a6-581d-94c1-ae8ee7f8a409
		summarizeBy: none
		sourceColumn: shrinkage_weight

		annotation SummarizationSetBy = User

	column shrunk_minutes_per_incident
		dataType: double
		formatString: 0.00
		lineageTag: 16145327-57f2-55cd-9aa7-80480afa66ae
		summarizeBy: none
		sourceColumn: shrunk_minutes_per_incident

		annotation SummarizationSetBy = User

	column count_rank
		dataType: int64
		formatString: 0
		lineageTag: e1fca3a6-b489-5b15-b1d4-41c094291577
		summarizeBy: none
		sourceColumn: count_rank

		annotation SummarizationSetBy = User

	column naive_rank
		dataType: int64
		formatString: 0
		lineageTag: 0f1ff29d-bca3-5af1-9822-19615be85219
		summarizeBy: none
		sourceColumn: naive_rank

		annotation SummarizationSetBy = User

	column shrunk_rank
		dataType: int64
		formatString: 0
		lineageTag: 2f133d14-c853-507a-a7d9-a07bb00ec6d2
		summarizeBy: none
		sourceColumn: shrunk_rank

		annotation SummarizationSetBy = User

	column rank_change
		dataType: int64
		formatString: 0
		lineageTag: 888a1ff9-c8a0-5dff-900f-2efecc8f51ed
		summarizeBy: none
		sourceColumn: rank_change

		annotation SummarizationSetBy = User

	column explanation
		dataType: string
		lineageTag: bd9ed075-f19a-5c42-9832-a4e7fc026824
		summarizeBy: none
		sourceColumn: explanation

		annotation SummarizationSetBy = User

	partition station_ranking = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\station_ranking.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.TransformColumns(Promoted, {}, each if _ = "" then null else _),
				    Typed = Table.TransformColumnTypes(Blanks, {{"period", type text}, {"period_sort", Int64.Type}, {"period_start", type date}, {"period_end", type date}, {"station_key", Int64.Type}, {"station_label", type text}, {"line_code", type text}, {"incidents", Int64.Type}, {"delay_minutes", type number}, {"naive_minutes_per_incident", type number}, {"line_minutes_per_incident", type number}, {"within_variance", type number}, {"line_within_variance", type number}, {"between_variance", type number}, {"shrinkage_weight", type number}, {"shrunk_minutes_per_incident", type number}, {"count_rank", Int64.Type}, {"naive_rank", Int64.Type}, {"shrunk_rank", Int64.Type}, {"rank_change", Int64.Type}, {"explanation", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
